### ISSUE TITLE
Change which arrows to display

### ISSUE THREAD

**Issue by fplgusmao** [vqv/ggbiplot#14]
Hello

I am using ggbiplot and I get this result
![result](https://cloud.githubusercontent.com/assets/8159837/8009957/3ad399c6-0ba4-11e5-80b3-36f5cfa2cbde.JPG)

You see all those arrows? I want to display only one of them. But I just want to get rid of the arrows, and not the data that originates them. Is there something I could do to customize the result?

**Comment by vqv** [comment]
I recommend using the experimental branch of ggbiplot: https://github.com/vqv/ggbiplot/tree/experimental

**Comment by fplgusmao** [comment]
Will give it a try. Thanks!
