### ISSUE TITLE
Provide option to sample plotted observations

### ISSUE THREAD

**Issue by MaxGhenis** [vqv/ggbiplot#21]
Currently `ggbiplot` plots all observations. I have a PCA model built on 1M observations, so would like to plot a random sample of them, typically as # not %.

**Comment by vqv** [comment]
The best way to accomplish this is to use the experimental branch of ggbiplot.  That will give you more control over what is plotted.  I have moved my effort to the experimental branch and will not add subsampling or any additional functionality to current branch of ggbiplot().
