### ISSUE TITLE
Color point outline based on data

### ISSUE THREAD

**Issue by dlennon** [vqv/ggbiplot#23]
I have passed a dataset to prcomp() to create a fit for PCA.

I use ggbiplot() to plot the figure as follows:

pop_pca <- ggbiplot(fit,obs.scale = 1, var.scale=1,groups=Patients,ellipse=T,circle=T,
                    varname.size=0, var.axes = FALSE)+
scale_colour_manual(values=colors)+guides(fill=guide_legend(nrow=2,byrow=TRUE))
pop_pca <- pop_pca + theme_bw() 

I would like to alter the outline of each point in the plot based on values in a second dataset. The second dataset has values for each point in the first dataset. Is this possible with ggbiplot()?

**Comment by vqv** [comment]
I recommend using the experimental branch of ggbiplot.  It will allow you to do what you want.
