### ISSUE TITLE
error when trying to install ggbiplot

### ISSUE THREAD

**Issue by jahneldardavik** [vqv/ggbiplot#59]
Could anyone please solve this issue for me? I would be much obliged!

> library(devtools)
Loading required package: usethis
Warning messages:
1: package ‘devtools’ was built under R version 3.6.1 
2: package ‘usethis’ was built under R version 3.6.1 
> install_github('vqv/ggbiplot',force =T)
Downloading GitHub repo vqv/ggbiplot@master
√  checking for file 'C:\Users\jada\AppData\Local\Temp\Rtmp8aKj9q\remotes315473d66def\vqv-ggbiplot-7325e88/DESCRIPTION' ...
-  preparing 'ggbiplot':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'ggbiplot_0.55.tar.gz'
   
Installing package into ‘C:/Users/jada/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'ggbiplot' ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ggplot2' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'ggbiplot'
* removing 'C:/Users/jada/Documents/R/win-library/3.6/ggbiplot'
Error: Failed to install 'ggbiplot' from GitHub:
  (converted from warning) installation of package ‘C:/Users/jada/AppData/Local/Temp/Rtmp8aKj9q/file3154684336ea/ggbiplot_0.55.tar.gz’ had non-zero exit status
>

**Comment by washfaq** [comment]
Hello,
I am also facing the same issue while installing "ggbiplot", can anybody help me with this issue? Thanks

**Comment by karenvbeaman** [comment]
I also get the same error.  It appears that ggbiplot is not available for R version 3.6?  Does anyone know when it might be upgraded?

**Comment by Shreeram38** [comment]
Installing package into �C:/Users/shree/OneDrive/Documents/R/win-library/3.6�
(as �lib� is unspecified)
* installing *source* package 'ggbiplot' ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ggplot2' was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package 'ggbiplot'
* removing 'C:/Users/shree/OneDrive/Documents/R/win-library/3.6/ggbiplot'
installation of package �C:/Users/shree/AppData/Local/Temp/RtmpqSRj03/filec3c3a2924b1/ggbiplot_0.55.tar.gz� had non-zero exit status


this is the same error i am facing when i am trying to install the ggbiplot package. please help me out ??

**Comment by Shreeram38** [comment]
library(devtools)
install_github("vqv/ggbiplot")

i used these commands to install the package.

**Comment by Jenna77** [comment]
Did anyone solve this, I am having the same issue?

**Comment by jahneldardavik** [comment]
No, I have not been able to resolve this one.
I have used another laptop with the R 3.5.3 installed, and on that one ggbiplot runs fine. However, that laptop has other issues (like won’t let me use car’).
Any help on the ggbiplot is greatly appreciated.

Fra: Jenna77 <notifications@github.com>
Sendt: mandag 2. mars 2020 19.39
Til: vqv/ggbiplot <ggbiplot@noreply.github.com>
Kopi: Jahn Davik <jahn.davik@nibio.no>; Author <author@noreply.github.com>
Emne: Re: [vqv/ggbiplot] error when trying to install ggbiplot (#59)


Did anyone solve this, I am having the same issue?

**Comment by karenvbeaman** [comment]
I solved this by following Dumas' comment, which I repeat here for you:
-------------
Hey guys! My colleague was also struggling with this so I helped him figure
it out.

You don't need to get functions from packages for them to work. You can
entre them manually.

What I suggested he did is to go to https://github.com/vqv/ggbiplot
and download the zip file ("clone or download"). In the zip file you'll
find a folder called R. In this folder are two R scripts.
Open these two and just run them.
This is the manual way of creating the function ggbiplot.

Hopefully I explained it well enough.

Kind regards!
Dumas

----------

THIS WORKED WELL FOR ME!

*Good luck!*
*Karen *

**Comment by washfaq** [comment]
Hi,
I am using latest version of R, I used below codes and it works well on my laptop.

install.packages("remotes")
remotes::install_github("vqv/ggbiplot")

**Comment by jahneldardavik** [comment]
Did it for me.
Thank you !

Fra: Karen V. Beaman <notifications@github.com>
Sendt: mandag 2. mars 2020 20.04
Til: vqv/ggbiplot <ggbiplot@noreply.github.com>
Kopi: Jahn Davik <jahn.davik@nibio.no>; Author <author@noreply.github.com>
Emne: Re: [vqv/ggbiplot] error when trying to install ggbiplot (#59)

I solved this by following Dumas' comment, which I repeat here for you:
-------------
Hey guys! My colleague was also struggling with this so I helped him figure
it out.

You don't need to get functions from packages for them to work. You can
entre them manually.

What I suggested he did is to go to https://github.com/vqv/ggbiplot
and download the zip file ("clone or download"). In the zip file you'll
find a folder called R. In this folder are two R scripts.
Open these two and just run them.
This is the manual way of creating the function ggbiplot.

Hopefully I explained it well enough.

Kind regards!
Dumas

----------

THIS WORKED WELL FOR ME!

*Good luck!*
*Karen *

**Comment by jahneldardavik** [comment]
I used the approach suggested by Karen / Dumas. It worked! Using the standard approach did not work on my laptop (fairly new and Windows 10).
Thanks for all responses.

jahn

**Comment by Shuang-Plum** [comment]
You can locate the tar.gz file in your local folder according to the error message. And then install the package directly with that tar.gz file: install.packages("C:/Users/...(put your local path here)/ggbiplot_0.55.tar.gz", repos = NULL, type = "source"). It should work.

**Comment by JamesMak11** [comment]
I am still failing to load/launch SensMap (the ggbiplot package) even after following Dumas method
![Error Occured ggbiplot](https://github.com/vqv/ggbiplot/assets/147182025/3dc065f8-42f3-4004-a524-d509cc867726)

Any help?
