### ISSUE TITLE
Installion error

### ISSUE THREAD

**Issue by msgoussi** [vqv/ggbiplot#71]
devtools::install_github("vqv/ggbiplot")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 29/60
  Rate limit reset at: 2021-12-05 14:39:04 UTC

**Comment by ssefick** [comment]
This looks like a credential problem? I believe GitHub changed something
related to theses not that long ago.

Stephen Sefick, PhD

**Comment by msgoussi** [comment]
Do you have any idea to solve this issue????

**Comment by ssefick** [comment]
I do not remember how I solved this problem. Good luck!

Stephen Sefick, PhD

**Comment by msgoussi** [comment]
Sys.setenv(GITHUB_PAT = 'github_key)
